services:
  
  tm-scraper:
    image: tm-scraper-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: tm-scraper
    # volumes:
    #   - ./services/libs/tm_scraper/storage/monitoring_data:/app/backend/assets/monitoring_data
    #   - ./services/libs/tm_scraper/storage/data_path:/app/backend/assets/data_path
    #   - ./services/libs/tm_scraper/storage/parsed_data_path:/app/backend/assets/parsed_data_path
    #   - ./storage/csv_data_path:/app/backend/assets/csv_data_path
    ports:
      - "8959:8959"
    stdin_open: true
    tty: true
