# Use the official PostgreSQL client image from Docker Hub
FROM postgres:latest


# Install psql client package
# RUN apt-get update && apt-get install -y postgresql-client
# CMD [ "psql","-U tefos -d tmdb" ]
